"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a_+t3h=+vfdb62opn22f#p^q-0almf))s&bok2x7wao0ft4-l0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders', # <-- Añadir aquí
    'gyms', # <-- nueva app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'keycloak',        # El nombre de la DB 
        'USER': 'admin_db',        # El usuario
        'PASSWORD': 'password_db', # La contraseña
        'HOST': 'postgres-db',     # El nombre del contenedor de Postgres
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURACIÓN DE SEGURIDAD (KEYCLOAK) ---

# Estos son los datos del "búnker" en Keycloak
KEYCLOAK_SERVER_URL = "http://localhost:8080/"
KEYCLOAK_REALM = "CaliSaaS"
KEYCLOAK_CLIENT_ID = "calisaas-backend"
KEYCLOAK_CLIENT_SECRET = "Pz096f5UL1I3eF1hYYk8O27Bz5L9nfp7" # llave aquí!

# Configuramos Django REST Framework para que pida "carnet" (Token)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', 
    ),
}

SIMPLE_JWT = {
    'ALGORITHM': 'RS256',
    'JWK_URL': 'http://keycloak:8080/realms/CaliSaaS/protocol/openid-connect/certs',
    'AUTH_HEADER_TYPES': ('Bearer',),
    
    # --- AJUSTES DE TOLERANCIA CRÍTICOS ---
    'VERIFY_ISSUER': False,    # Ignora si el token dice "localhost" o "keycloak"
    'VERIFY_AUDIENCE': False,  # Ignora si el token es para 'account' o 'calisaas-backend'
    'TOKEN_TYPE_CLAIM': None,  # Keycloak no siempre manda el campo 'typ' como Django quiere
    'JTI_CLAIM': None,         # Evita errores si el ID único del token no coincide
    'LEEWAY': 300,             # Damos 5 minutos de margen por si los relojes de Docker están mal
    
    'USER_ID_FIELD': 'username',
    'USER_ID_CLAIM': 'preferred_username',
}

# --- CONFIGURACIÓN DE CORS ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Puerto estándar de React
    "http://localhost:5173", # Puerto estándar de Vite (React/Vue)
]
