version: '3.8'

services:
  db_gimnasio_norte_pg:
    image: postgres:15
    container_name: db_gimnasio_norte_pg
    environment:
      POSTGRES_DB: gimnasio_norte
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared_network

  db_gimnasio_sur_mysql:
    image: mysql:8.0
    container_name: db_gimnasio_sur_mysql
    environment:
      MYSQL_DATABASE: gimnasio_sur
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db_gimnasio_norte_pg:5432/gimnasio_norte
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8082:8080"
    depends_on:
      - db_gimnasio_norte_pg
    networks:
      - shared_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - shared_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shared_network



  api_norte:
    build:
      context: ./tenant_norte_python
    container_name: api_norte
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db_gimnasio_norte_pg
      - DB_PORT=5432
      - DB_NAME=gimnasio_norte
      - DB_USER=user
      - DB_PASSWORD=password
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - db_gimnasio_norte_pg
      - kafka
    networks:
      - shared_network

  api_sur:
    build:
      context: ./tenant_sur_node
    container_name: api_sur
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db_gimnasio_sur_mysql
      - DB_PORT=3306
      - DB_NAME=gimnasio_sur
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - db_gimnasio_sur_mysql
      - kafka
    networks:
      - shared_network

  auditoria:
    build:
      context: ./ms_auditoria_simple
    container_name: auditoria
    restart: always
    environment:
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - kafka
    networks:
      - shared_network
    volumes:
      - ./ms_auditoria_simple/auditoria.log:/app/auditoria.log

  frontend:
    build:
      context: ./frontend-angular
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend-angular:/app
      - /app/node_modules
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

volumes:
  pg_data:
  mysql_data:
