# Generated by Django 4.2.29 on 2026-04-06 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='owner_email',
        ),
        migrations.AddField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_gyms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
